[package]
name = "account-serialization"
version = "0.1.0"
edition = "2024"

[dependencies]

solana-sdk="1.18"
solana-program="1.18"
solana-client="1.18"
solana-transaction-status = "1.18.0"
clap={version="4.0",features=["derive"]}
anyhow="1.0"
bytemuck = "1.23.2"
thiserror = "2.0.17"





